// <auto-generated />
namespace DynamicMenuMVC.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class DataInitilize : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DataInitilize));
        
        string IMigrationMetadata.Id
        {
            get { return "202103210642537_DataInitilize"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
